#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := fyrtur-esp8266

EXTRA_COMPONENT_DIRS = $(PROJECT_PATH)/../../components
EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/../main

include ../../components/node-framework/iot.mk

include $(IDF_PATH)/make/project.mk

